### ISSUE TITLE
Use "detailed" info-level

### ISSUE THREAD

**Issue by sualeh** [meridsa/schemacrawler-bugs#1]
@meridsa 
With respect to https://github.com/schemacrawler/SchemaCrawler/issues/1432

Please see ["repro-bug.sh"](https://github.com/meridsa/schemacrawler-bugs/blob/master/repro-bug.sh#L75) where you should be using at least `--info-level=detailed` (or one level up, `--info-level=maximum`). You can use either the "schema" or the "detailed" command.

**Comment by meridsa** [comment]
This works! Thanks!
